### ISSUE TITLE
Development Logs

### ISSUE THREAD

**Issue by al8n** [al8n/ruraft#10]
# TODOs

###  Tier 1
- [x] Clean up `Error` constructors #13
- [x] Adapt to `CheapClone` changes https://github.com/al8n/nodecraft/issues/1
- [x] Cleanup shutdown logic and warnings #11
- [x] Add `MembershipBuilder` and make `Membership` immutable #13
- [x] Transport support
    - [x] Adapt to `core`'s `Transport` trait changes #14 
    - [x] TLS support #15
    - [ ] QUIC transport support
        - [ ] [`quinn`](https://crates.io/crates/quinn)
        - [ ] [`s2n`](https://crates.io/crates/s2n-quic)
- [x] `metrics` cleanup #18
- [ ] Storage support
    - [x] `ruraft-lightwal` #19
        - [x] [`sled`](https://crates.io/crates/sled) backend
        - [x] [`jammdb`](https://crates.io/crates/jammdb) backend
        - [x] [`redb`](https://crates.io/crates/redb) backend
    - [ ] [`ruraft-wal`](https://github.com/hashicorp/raft-wal) #20
        - [ ] [`sled`](https://crates.io/crates/sled) backend
        - [ ] [`jammdb`](https://crates.io/crates/jammdb) backend
        - [ ] [`redb`](https://crates.io/crates/redb) backend
- [ ] Add `pre_vote` support
- [ ] Implement raft autopilot https://github.com/hashicorp/raft-autopilot
- [ ] Tests
     - [ ] Unit tests
        - [ ] Unit tests for `Transport` implementations
            - [x] TCP/TLS #25
            - [ ] quinn
            - [ ] s2n
         - [ ] Unit tests for `RaftCore` implementation
     - [ ] Integration test
     - [ ] Fuzzy test

### Tier 2
- [ ] Use zero capacity channels https://github.com/smol-rs/async-channel/issues/58
- [ ] Do not use `thiserror` for `Error` implementation. Implement `Error` in `std::io::Error` style.
- [ ] Implement raft chunking https://github.com/hashicorp/go-raftchunking
- [ ] FFI support
    - [ ] WASI
    - [ ] Python
    - [ ] NodeJS

## Documentation
- [ ] Tutorials
